# Generated by Django 5.2.4 on 2025-08-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('duration', models.CharField(max_length=20)),
                ('departure_location', models.CharField(max_length=100)),
                ('transportation', models.CharField(max_length=50)),
                ('start_dates', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
    ]
